server:
  port: 8085

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:3333/ea-product-db
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

ping:
  message: "Product service ping successful !!"
