server:
  port: 8084

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:2222/ea-user-db
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

welcome:
  message: "Reading message from the config server"
